const FECTH_DATA = "FETCH_DATA";
const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
const SET_MENU_OPTIONS = "SET_MENU-OPTIONS";
const SAVE_DATA_FILTER = "SAVE_DATA_FILTER";
const GET_CURRENT_PAGE = "GET_CURRENT_PAGE";
const AUTH_REQUEST = 'AUTH_REQUEST';
export {
  FECTH_DATA,
  FETCH_DATA_REQUEST,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAILURE,
  SET_MENU_OPTIONS,
  SAVE_DATA_FILTER,
  GET_CURRENT_PAGE,
  AUTH_REQUEST
};
